---
# This playbook configures other roles

- name: setup ldap server role
  hosts: role_ldap_server
  become: yes
  become_user: root
  roles:
    - ldap_server

- name: setup cribl server role
  hosts: role_cribl_server
  become: yes
  become_user: root
  roles:
    - cribl_server

- name: correct splunk outputs confs for the use of cribl server
  hosts: role_cluster_master,role_deployer,role_deployment_server,role_license_master,role_monitoring_console,role_search_head,role_universal_forwarder
  become: yes
  become_user: root
  roles:
    - cribl_environment_reconfig

